import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Arrow from "./components/Arrow";
import Fab from "./components/Fab";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="navbar">
                    <Arrow location="/"></Arrow>
                    <Link href="/">home</Link>
                    <Link href="/button">button</Link>
                    <Link href="/object">object</Link>
                    <Link href="/mongo">mongo</Link>
                    <Link href="/write">write</Link>
                    <Link href="/signup">signup</Link>
                    <Fab></Fab>
                </div>
                {children}
            </body>
        </html>
    );
}
